version: "3"

services:
  postgres:
    image: postgres
    environment:
      POSTGRES_PASSWORD: "123456"
      POSTGRES_USER: "root"
    ports:
      - "5432:5432"
  nodejs:
    build: .
    image: nodejs:20.10.0
    container_name: nodejs
    env_file: .env
    environment:
      - DATABASE_URL=$DATABASE_URL
    ports: ["3000:3000"]
    volumes:
      - .:/home/node/app